### ISSUE TITLE
Thoughts on module separation.

### ISSUE THREAD

**Issue by raizyr** [newcontext-oss/kitchen-terraform#111]
It seems that most of the community discussion that I've seen thus var around modules is to use a separate `terraform-modules` repo for reusable components and a `terraform-live` repo for live infrastructure code.

Since `kitchen-terraform` is a set of plugins for `test-kitchen` and the accepted way to handle chef cookbooks is a cookbook per repo, is it then better to use that idea for terraform modules as well?  Instead of a single `terraform-modules` repo, should we be creating several smaller repos for each module?

**Comment by ncs-alane** [comment]
@raizyr:

I think independent modules are good candidates for unique repositories. Splitting up monolithic repositories can encourage stronger design of module interfaces because there will be less implicit context of other modules that may exist in the same graph. kitchen-terraform should be flexible enough to support both modular and monolithic code bases, though.

**Comment by raizyr** [comment]
Ok, that lines up with what I was thinking.  Thanks!
