### ISSUE TITLE
RFC: Is the ruby 2.2 customer / user requirement really needed or can we push forward with closer integration with kitchen-inspec mainline?

### ISSUE THREAD

**Issue by aaronlippold** [newcontext-oss/kitchen-terraform#175]
* Please do a poll to find out if this pinning is really need

Value back: 

The kitchen-terraform project will not get as much value from the inspec platform resources that are coming out very soon - such as aws or azure or gcs etc - without having to do out of band integration to backport these into the inspec pinned version that is currently being used.

If we are able to keep things sync'd then we should inherit this automatically with no real extra work on our side and showing large value to the kitchen-terraform user base.

**Comment by ncs-alane** [comment]
**All users!** Please vote on this comment to indicate your support for this request.

:+1: drop support for Ruby 2.2 as soon as possible to enable support for InSpec >= 1.44.8

:-1: maintain support for Ruby 2.2 until it reaches end of life on 2018-03-31

**Comment by nictrix** [comment]
Dropping support is less than ideal, however thinking about Terraform modules, they are not Ruby projects and most likely will not have a Ruby 2.2 dependency outside of kitchen-terraform.

**Comment by brandoconnor** [comment]
Though I'm in favor of eventually dropping support of 2.2, I don't see an urgent need to do it. I think it makes sense to time it with the availability of the new inspec resources.

@aaronlippold do you have any idea on the timeline of those being released?

**Comment by aaronlippold** [comment]
@brandoconnor we hope to release them soon after the new year. The inspec team is evaluating if the ruby 2.2 drop is really what they want to do so at this point I think we should just wait and see and once the inspec team decides on a direction then we will know if this is an issue or not.

**Comment by ringods** [comment]
I'm not an avid Ruby developer, so I want to stay away from RVM/rbenv and Gemfiles. I just download ChefDK which for me delivers a consistent setup of all the required tooling.

I then run `chef gem install kitchen-terraform --version=3.0.0` but the driver fails to load due to this:

```
E, [2017-12-31T12:01:12.327403 #37392] ERROR -- Kitchen: Class: Gem::ConflictError
E, [2017-12-31T12:01:12.327419 #37392] ERROR -- Kitchen: Message: Unable to activate kitchen-terraform-3.0.0, because inspec-1.45.13 conflicts with inspec (<= 1.44.8, >= 0.34.0), test-kitchen-1.19.2 conflicts with test-kitchen (~> 1.16.0)
```

Here are the version of some of the dependencies in ChefDK 2.4.17:

```
gem "inspec", "= 1.45.13"
gem "kitchen-inspec", "= 0.20.0"
gem "test-kitchen", "= 1.19.2"
```

Also, looking at the Ruby website, version 2.2.9 is mentioned as `In security maintenance phase (will EOL soon!)`. Would it be possible to drop the upper bound on the `inspec` version requirement so non-2.2 users can go forward, while the 2.2 users could still lock a version in their local `Gemfile` or `*.gemspec` file?

**Comment by aaronlippold** [comment]
Great to see this moving forward - it will help integration across all three projects. Thanks @ncs-alane and team for being open and responsive to this.
