### ISSUE TITLE
Expose Terraform variables as InSpec attributes

### ISSUE THREAD

**Issue by tomelliff** [newcontext-oss/kitchen-terraform#205]
Kitchen-Terraform allows access to Terraform output variables by linking them to InSpec variables with something like:
```ruby
terraform_state =
  # The Terraform configuration under test must define the equivalently named
  # output
  attribute(
    "terraform_state",
    description: "The path to the Terraform state file"
  )
```
assuming a Terraform output configured as:
```hcl
output "terraform_state" {
  description = "The path to the Terraform state file"

  value = "${path.cwd}/terraform.tfstate.d/${terraform.workspace}/terraform.tfstate"
}
```
If we want to access input variables defined in a vars.tf (and potentially set/overridden by the driver variables) we need to create an output with the value of the input variable like this:
```hcl
output "my_input_variable" {
  value = "${var.my_input_variable}"
}
```
It would be nice to at least skip the definition of this output and simply access it directly as:
```ruby
my_input_variable =
  attribute(
    "my_input_variable", {}
  )
```

When discussing this with @ncs-alane in Gitter he pointed out that we would have to be aware of clashing with output variables here. I'd propose prepending `input_` or `output_` to input and output variables respectively (with the default of looking for output variables if neither is specified, maybe searching for input variables if an output variable isn't found that matches that name) if this is deemed a risk.

So we might have something like this:
```hcl
module "my_module" {
  source = "../../../"

  input_var = "${var.my_input_variable}"
}

output "terraform_state" {
  description = "The path to the Terraform state file"

  value = "${path.cwd}/terraform.tfstate.d/${terraform.workspace}/terraform.tfstate"
}

output "my_output_variable" {
  value = "${module.my_module.output_var}"
}
```
which we could access with either:
```ruby
my_input_variable =
  attribute(
    "my_input_variable", {}
  )

my_output_variable =
  attribute(
    "my_output_variable", {}
  )
```
or:
```ruby
my_input_variable =
  attribute(
    "input_my_input_variable", {}
  )

my_output_variable =
  attribute(
    "output_my_output_variable", {}
  )
```

**Comment by ncs-alane** [comment]
@tomelliff thank you for the comprehensive description!

I think that prepending `input` and `output` to the attribute names is a reasonable approach to differentiating between the two sources. We could leave the unqualified names resolving to output values to introduce this feature in a minor version, but I would prefer to eventually remove that behaviour in a major version rather than also falling back to input values in order to reduce surprising behaivour. 

We will need to indentify an approach that allows us to obtain all input values rather than just those provided through the driver's `variables` attribute.
