### ISSUE TITLE
delegate-0.2.0 undefined method

### ISSUE THREAD

**Issue by brettcurtis** [newcontext-oss/kitchen-terraform#513]
Howdy!

Somewhat recently, I started getting an error when running kitchen:

```none
bundle exec kitchen converge
/home/brett/.gem/gems/delegate-0.2.0/lib/delegate.rb:48:in `undef_method': undefined method `=~' for module `#<Module:0x00007f17b9c096a8>' (NameError)
```

If I delete the file listed above kitchen runs fine. Is this something in my local messed up or a dependency issue? 

My Gemfile:

```none
source 'https://rubygems.org'
gem 'kitchen-terraform'
gem 'inspec'
gem 'rubocop'
```

Thanks!

**Comment by aaron-lane** [comment]
Hello again @brettcurtis 👋🏼 

I also encountered this issue recently. I think it may have been an incompatibility between Test Kitchen and Ruby 3.2. Can you confirm the version of Ruby that you're using, the version of the `test-kitchen` gem in your `Gemfile.lock`, and if you still see the issue if you source the `kitchen-terraform` gem from the `main` branch of this repository instead of Ruby Gems?

**Comment by brettcurtis** [comment]
```none
❯ ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
❯ cat ~/Gemfile.lock|grep test-kitchen
      test-kitchen (>= 2.1, < 4.0)
    test-kitchen (3.5.0)
```

And yes, works of the main branch, thanks bud!

**Comment by aaron-lane** [comment]
Excellent 🎉  I hope to cut the new version of the gem this week.

**Comment by aaron-lane** [comment]
So we'll mark this as fixed by #509, though it may have been fixed earlier 🤭

**Comment by wyardley** [comment]
@aaron-lane any news on new release?

**Comment by aaron-lane** [comment]
I should have some down time tomorrow to cut a release 🤞🏼Unpaid labour and all that 😜

**Comment by wyardley** [comment]
Woo, thanks @aaron-lane. Appreciated!
